### ISSUE TITLE
How should setup actions be handled?

### ISSUE THREAD

**Issue by MrToph** [MrToph/eosiac#2]
It would be useful to be able to run actions (after specific events?) like issuing a token upon deploying a token contract.

Let's discuss the best way to approach this.

**Comment by MrToph** [comment]
Was thinking about a `hooks` field similar to this:

```yaml
  accounts:
    dapptoken:
      code: contracts/dapptoken/dapptoken.wasm
      abi: contracts/dapptoken/dapptoken.abi
      hooks:
        after_deploy:
            - transaction1
            - transaction2
```
